### PR TITLE
Add Rust container

### PR DESCRIPTION
**Pull request by tenten8401**

### CODE REVIEW

**Comment by DaneEveritt** [comment]
Why are you including an entire node_modules folder?

**Comment by tenten8401** [comment]
They're needed for the wrapper.js to function properly.

**Comment by DaneEveritt** [comment]
Is there a reason they cannot be installed inside the container itself during the creation process, rather than copied into it?

**Comment by tenten8401** [comment]
OxideMod isn't finished yet, there are still some things that need to be worked out. Will work on this tomorrow.

**Comment by schrej** [comment]
As this was tested with the related PR (Pterodactyl/Panel#537) this is getting merged as well.

**Comment by schrej** [comment]
@DaneEveritt The automatic build on quay.io needs to be set up for this probably.

**Comment by DaneEveritt** [comment]
Its already configured. 👌

**Pull request merged**
